### ISSUE TITLE
Update these code samples to work with SDK 12.2.0

### ISSUE THREAD

**Issue by robertmassaioli** [NordicSemiconductor/nrf51-ADC-examples#4]
The methods and functions in 12.2.0 are nicer than the methods in 11.0.0. It's the little things, like the `nrf_drv_timer_ms_to_ticks` method for example.

Could we update all of these sample apps to work with 12.2.0? Is there a reason that we should not do that? I've bought some legacy nRF51822 devices; I know that they are technically deprecated parts but they are excellently priced and should be possible to use to get the job done so I want to try and use the latest SDK with them if possible.

**Comment by jorhol** [comment]
Examples updated for SDK 12.2.0.
